name: Test
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Make a file with a lot of repeated text
        run: |
          dd if=/dev/urandom of=my-1gb-file bs=1M count=10
      - uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          generateReleaseNotes: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: my-1gb-file
